title: detohm
email: ""
description: >- 
  I'm Coder, CTO, DevOps, Geek and Introvert.
baseurl: "" 
url: "https://detohm.io" 


excerpt_separator: "<!-- readmore -->"
markdown: kramdown

disqus:
  shortname: detohm-io

plugins:
  - jekyll-feed
  - jekyll-seo-tag
